# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cluster Innovation Centre, University of Delhi
email: dev@one.ducic.ac.in
description: > # this means to ignore newlines until "baseurl:"
  University of Delhi has set up Cluster Innovation Centre (CIC) with the
  objective of fostering an ecosystem of innovation and connecting research
  with application for the benefit of society. The CIC aims to support
  application oriented research to solve real world problems by developing
  ideas into innovative applications that can be commercialized successfully.
baseurl: ""
url: "https://ducic.ac.in" # the base hostname & protocol for your site
github_username:  ClusterInnovationCentre

# Build settings
markdown: kramdown
